//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63135935.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
        }
    
        public string MaSach { get; set; }
        public string MaLoaiSach { get; set; }
        public string TenSach { get; set; }
        public string AnhSach { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string TacGia { get; set; }
        public string NhaXuatBan { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> NgayXuatBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual LoaiSach LoaiSach { get; set; }
    }
}
